//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Locations
    {
        public System.Guid Id { get; set; }
        public System.Guid Company { get; set; }
        public string Country_Code { get; set; }
        public string State_Province_Code { get; set; }
        public string Street_Address { get; set; }
        public string City_Town { get; set; }
        public string Zip_Postal_Code { get; set; }
        public byte[] Time_Stamp { get; set; }
    
        public virtual Company_Profiles Company_Profiles { get; set; }
    }
}
