//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Descriptions
    {
        public System.Guid Id { get; set; }
        public System.Guid Company { get; set; }
        public string LanguageID { get; set; }
        public string Company_Name { get; set; }
        public string Company_Description { get; set; }
        public byte[] Time_Stamp { get; set; }
    
        public virtual Company_Profiles Company_Profiles { get; set; }
        public virtual System_Language_Codes System_Language_Codes { get; set; }
    }
}
