//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Job_Educations
    {
        public System.Guid Id { get; set; }
        public System.Guid Job { get; set; }
        public string Major { get; set; }
        public short Importance { get; set; }
        public byte[] Time_Stamp { get; set; }
    
        public virtual Company_Jobs Company_Jobs { get; set; }
    }
}
