//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JOB_PORTAL_DBEntities : DbContext
    {
        public JOB_PORTAL_DBEntities()
            : base("name=JOB_PORTAL_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applicant_Educations> Applicant_Educations { get; set; }
        public virtual DbSet<Applicant_Job_Applications> Applicant_Job_Applications { get; set; }
        public virtual DbSet<Applicant_Profiles> Applicant_Profiles { get; set; }
        public virtual DbSet<Applicant_Resumes> Applicant_Resumes { get; set; }
        public virtual DbSet<Applicant_Skills> Applicant_Skills { get; set; }
        public virtual DbSet<Applicant_Work_History> Applicant_Work_History { get; set; }
        public virtual DbSet<Company_Descriptions> Company_Descriptions { get; set; }
        public virtual DbSet<Company_Job_Educations> Company_Job_Educations { get; set; }
        public virtual DbSet<Company_Job_Skills> Company_Job_Skills { get; set; }
        public virtual DbSet<Company_Jobs> Company_Jobs { get; set; }
        public virtual DbSet<Company_Jobs_Descriptions> Company_Jobs_Descriptions { get; set; }
        public virtual DbSet<Company_Locations> Company_Locations { get; set; }
        public virtual DbSet<Company_Profiles> Company_Profiles { get; set; }
        public virtual DbSet<Security_Logins> Security_Logins { get; set; }
        public virtual DbSet<Security_Logins_Log> Security_Logins_Log { get; set; }
        public virtual DbSet<Security_Logins_Roles> Security_Logins_Roles { get; set; }
        public virtual DbSet<Security_Roles> Security_Roles { get; set; }
        public virtual DbSet<System_Country_Codes> System_Country_Codes { get; set; }
        public virtual DbSet<System_Language_Codes> System_Language_Codes { get; set; }
    }
}
