//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_Logins_Roles
    {
        public System.Guid Id { get; set; }
        public System.Guid Login { get; set; }
        public System.Guid Role { get; set; }
        public byte[] Time_Stamp { get; set; }
    
        public virtual Security_Logins Security_Logins { get; set; }
        public virtual Security_Roles Security_Roles { get; set; }
    }
}
