//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.UnitTests.Assignment5.CompanyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.ICompany")]
    public interface ICompany {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyDescriptionResponse")]
        void AddCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyDescriptionResponse")]
        System.Threading.Tasks.Task AddCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyDescriptionResponse")]
        CareerCloud.Pocos.CompanyDescriptionPoco[] GetAllCompanyDescription();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco[]> GetAllCompanyDescriptionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyDescriptionResponse")]
        CareerCloud.Pocos.CompanyDescriptionPoco GetSingleCompanyDescription(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco> GetSingleCompanyDescriptionAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyDescriptionResponse")]
        void RemoveCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyDescriptionResponse")]
        System.Threading.Tasks.Task RemoveCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyDescriptionResponse")]
        void UpdateCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyDescriptionResponse")]
        System.Threading.Tasks.Task UpdateCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobDescriptionResponse")]
        void AddCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task AddCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobDescriptionResponse")]
        CareerCloud.Pocos.CompanyJobDescriptionPoco[] GetAllCompanyJobDescription();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco[]> GetAllCompanyJobDescriptionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobDescriptionResponse")]
        CareerCloud.Pocos.CompanyJobDescriptionPoco GetSingleCompanyJobDescription(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco> GetSingleCompanyJobDescriptionAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobDescriptionResponse")]
        void RemoveCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobDescriptionResponse")]
        void UpdateCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobEducationResponse")]
        void AddCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobEducationResponse")]
        System.Threading.Tasks.Task AddCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobEducationResponse")]
        CareerCloud.Pocos.CompanyJobEducationPoco[] GetAllCompanyJobEducation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobEducationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco[]> GetAllCompanyJobEducationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobEducationResponse")]
        CareerCloud.Pocos.CompanyJobEducationPoco GetSingleCompanyJobEducation(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobEducationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco> GetSingleCompanyJobEducationAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobEducationResponse")]
        void RemoveCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobEducationResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobEducationResponse")]
        void UpdateCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobEducationResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJob", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobResponse")]
        void AddCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJob", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobResponse")]
        System.Threading.Tasks.Task AddCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobResponse")]
        CareerCloud.Pocos.CompanyJobPoco[] GetAllCompanyJob();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco[]> GetAllCompanyJobAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobResponse")]
        CareerCloud.Pocos.CompanyJobPoco GetSingleCompanyJob(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco> GetSingleCompanyJobAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJob", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobResponse")]
        void RemoveCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJob", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJob", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobResponse")]
        void UpdateCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJob", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobSkillResponse")]
        void AddCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobSkillResponse")]
        System.Threading.Tasks.Task AddCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobSkillResponse")]
        CareerCloud.Pocos.CompanyJobSkillPoco[] GetAllCompanyJobSkill();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobSkillResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco[]> GetAllCompanyJobSkillAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobSkillResponse")]
        CareerCloud.Pocos.CompanyJobSkillPoco GetSingleCompanyJobSkill(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobSkillResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco> GetSingleCompanyJobSkillAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobSkillResponse")]
        void RemoveCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobSkillResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobSkillResponse")]
        void UpdateCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobSkillResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyLocation", ReplyAction="http://tempuri.org/ICompany/AddCompanyLocationResponse")]
        void AddCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyLocation", ReplyAction="http://tempuri.org/ICompany/AddCompanyLocationResponse")]
        System.Threading.Tasks.Task AddCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyLocationResponse")]
        CareerCloud.Pocos.CompanyLocationPoco[] GetAllCompanyLocation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyLocationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco[]> GetAllCompanyLocationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyLocationResponse")]
        CareerCloud.Pocos.CompanyLocationPoco GetSingleCompanyLocation(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyLocationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco> GetSingleCompanyLocationAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyLocation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyLocationResponse")]
        void RemoveCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyLocation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyLocationResponse")]
        System.Threading.Tasks.Task RemoveCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyLocation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyLocationResponse")]
        void UpdateCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyLocation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyLocationResponse")]
        System.Threading.Tasks.Task UpdateCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyProfile", ReplyAction="http://tempuri.org/ICompany/AddCompanyProfileResponse")]
        void AddCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyProfile", ReplyAction="http://tempuri.org/ICompany/AddCompanyProfileResponse")]
        System.Threading.Tasks.Task AddCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyProfileResponse")]
        CareerCloud.Pocos.CompanyProfilePoco[] GetAllCompanyProfile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyProfileResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco[]> GetAllCompanyProfileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyProfileResponse")]
        CareerCloud.Pocos.CompanyProfilePoco GetSingleCompanyProfile(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyProfileResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco> GetSingleCompanyProfileAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyProfile", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyProfileResponse")]
        void RemoveCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyProfile", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyProfileResponse")]
        System.Threading.Tasks.Task RemoveCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyProfile", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyProfileResponse")]
        void UpdateCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyProfile", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyProfileResponse")]
        System.Threading.Tasks.Task UpdateCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyChannel : CareerCloud.UnitTests.Assignment5.CompanyService.ICompany, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyClient : System.ServiceModel.ClientBase<CareerCloud.UnitTests.Assignment5.CompanyService.ICompany>, CareerCloud.UnitTests.Assignment5.CompanyService.ICompany {
        
        public CompanyClient() {
        }
        
        public CompanyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] items) {
            base.Channel.AddCompanyDescription(items);
        }
        
        public System.Threading.Tasks.Task AddCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] items) {
            return base.Channel.AddCompanyDescriptionAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyDescriptionPoco[] GetAllCompanyDescription() {
            return base.Channel.GetAllCompanyDescription();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco[]> GetAllCompanyDescriptionAsync() {
            return base.Channel.GetAllCompanyDescriptionAsync();
        }
        
        public CareerCloud.Pocos.CompanyDescriptionPoco GetSingleCompanyDescription(string Id) {
            return base.Channel.GetSingleCompanyDescription(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco> GetSingleCompanyDescriptionAsync(string Id) {
            return base.Channel.GetSingleCompanyDescriptionAsync(Id);
        }
        
        public void RemoveCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] items) {
            base.Channel.RemoveCompanyDescription(items);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] items) {
            return base.Channel.RemoveCompanyDescriptionAsync(items);
        }
        
        public void UpdateCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] items) {
            base.Channel.UpdateCompanyDescription(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] items) {
            return base.Channel.UpdateCompanyDescriptionAsync(items);
        }
        
        public void AddCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items) {
            base.Channel.AddCompanyJobDescription(items);
        }
        
        public System.Threading.Tasks.Task AddCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items) {
            return base.Channel.AddCompanyJobDescriptionAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyJobDescriptionPoco[] GetAllCompanyJobDescription() {
            return base.Channel.GetAllCompanyJobDescription();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco[]> GetAllCompanyJobDescriptionAsync() {
            return base.Channel.GetAllCompanyJobDescriptionAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobDescriptionPoco GetSingleCompanyJobDescription(string Id) {
            return base.Channel.GetSingleCompanyJobDescription(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco> GetSingleCompanyJobDescriptionAsync(string Id) {
            return base.Channel.GetSingleCompanyJobDescriptionAsync(Id);
        }
        
        public void RemoveCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items) {
            base.Channel.RemoveCompanyJobDescription(items);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items) {
            return base.Channel.RemoveCompanyJobDescriptionAsync(items);
        }
        
        public void UpdateCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items) {
            base.Channel.UpdateCompanyJobDescription(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items) {
            return base.Channel.UpdateCompanyJobDescriptionAsync(items);
        }
        
        public void AddCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] items) {
            base.Channel.AddCompanyJobEducation(items);
        }
        
        public System.Threading.Tasks.Task AddCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] items) {
            return base.Channel.AddCompanyJobEducationAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyJobEducationPoco[] GetAllCompanyJobEducation() {
            return base.Channel.GetAllCompanyJobEducation();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco[]> GetAllCompanyJobEducationAsync() {
            return base.Channel.GetAllCompanyJobEducationAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobEducationPoco GetSingleCompanyJobEducation(string Id) {
            return base.Channel.GetSingleCompanyJobEducation(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco> GetSingleCompanyJobEducationAsync(string Id) {
            return base.Channel.GetSingleCompanyJobEducationAsync(Id);
        }
        
        public void RemoveCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] items) {
            base.Channel.RemoveCompanyJobEducation(items);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] items) {
            return base.Channel.RemoveCompanyJobEducationAsync(items);
        }
        
        public void UpdateCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] items) {
            base.Channel.UpdateCompanyJobEducation(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] items) {
            return base.Channel.UpdateCompanyJobEducationAsync(items);
        }
        
        public void AddCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] items) {
            base.Channel.AddCompanyJob(items);
        }
        
        public System.Threading.Tasks.Task AddCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] items) {
            return base.Channel.AddCompanyJobAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyJobPoco[] GetAllCompanyJob() {
            return base.Channel.GetAllCompanyJob();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco[]> GetAllCompanyJobAsync() {
            return base.Channel.GetAllCompanyJobAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobPoco GetSingleCompanyJob(string Id) {
            return base.Channel.GetSingleCompanyJob(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco> GetSingleCompanyJobAsync(string Id) {
            return base.Channel.GetSingleCompanyJobAsync(Id);
        }
        
        public void RemoveCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] items) {
            base.Channel.RemoveCompanyJob(items);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] items) {
            return base.Channel.RemoveCompanyJobAsync(items);
        }
        
        public void UpdateCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] items) {
            base.Channel.UpdateCompanyJob(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] items) {
            return base.Channel.UpdateCompanyJobAsync(items);
        }
        
        public void AddCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] items) {
            base.Channel.AddCompanyJobSkill(items);
        }
        
        public System.Threading.Tasks.Task AddCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] items) {
            return base.Channel.AddCompanyJobSkillAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyJobSkillPoco[] GetAllCompanyJobSkill() {
            return base.Channel.GetAllCompanyJobSkill();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco[]> GetAllCompanyJobSkillAsync() {
            return base.Channel.GetAllCompanyJobSkillAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobSkillPoco GetSingleCompanyJobSkill(string Id) {
            return base.Channel.GetSingleCompanyJobSkill(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco> GetSingleCompanyJobSkillAsync(string Id) {
            return base.Channel.GetSingleCompanyJobSkillAsync(Id);
        }
        
        public void RemoveCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] items) {
            base.Channel.RemoveCompanyJobSkill(items);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] items) {
            return base.Channel.RemoveCompanyJobSkillAsync(items);
        }
        
        public void UpdateCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] items) {
            base.Channel.UpdateCompanyJobSkill(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] items) {
            return base.Channel.UpdateCompanyJobSkillAsync(items);
        }
        
        public void AddCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] items) {
            base.Channel.AddCompanyLocation(items);
        }
        
        public System.Threading.Tasks.Task AddCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] items) {
            return base.Channel.AddCompanyLocationAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyLocationPoco[] GetAllCompanyLocation() {
            return base.Channel.GetAllCompanyLocation();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco[]> GetAllCompanyLocationAsync() {
            return base.Channel.GetAllCompanyLocationAsync();
        }
        
        public CareerCloud.Pocos.CompanyLocationPoco GetSingleCompanyLocation(string Id) {
            return base.Channel.GetSingleCompanyLocation(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco> GetSingleCompanyLocationAsync(string Id) {
            return base.Channel.GetSingleCompanyLocationAsync(Id);
        }
        
        public void RemoveCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] items) {
            base.Channel.RemoveCompanyLocation(items);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] items) {
            return base.Channel.RemoveCompanyLocationAsync(items);
        }
        
        public void UpdateCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] items) {
            base.Channel.UpdateCompanyLocation(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] items) {
            return base.Channel.UpdateCompanyLocationAsync(items);
        }
        
        public void AddCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] items) {
            base.Channel.AddCompanyProfile(items);
        }
        
        public System.Threading.Tasks.Task AddCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] items) {
            return base.Channel.AddCompanyProfileAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyProfilePoco[] GetAllCompanyProfile() {
            return base.Channel.GetAllCompanyProfile();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco[]> GetAllCompanyProfileAsync() {
            return base.Channel.GetAllCompanyProfileAsync();
        }
        
        public CareerCloud.Pocos.CompanyProfilePoco GetSingleCompanyProfile(string Id) {
            return base.Channel.GetSingleCompanyProfile(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco> GetSingleCompanyProfileAsync(string Id) {
            return base.Channel.GetSingleCompanyProfileAsync(Id);
        }
        
        public void RemoveCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] items) {
            base.Channel.RemoveCompanyProfile(items);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] items) {
            return base.Channel.RemoveCompanyProfileAsync(items);
        }
        
        public void UpdateCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] items) {
            base.Channel.UpdateCompanyProfile(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] items) {
            return base.Channel.UpdateCompanyProfileAsync(items);
        }
    }
}
